[package]
name = "scanner"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
logger = { path = "../logger" }
lox = { path = "../lox" }
